"""turnstyl command line.

    turnstyl job new <contract.sol> --buyer <addr>
    turnstyl job run <job_id>
    turnstyl pay <job_id> <step> [--tx <hash>]
    turnstyl ledger <buyer>
    turnstyl status
    turnstyl reset --db <path>
    turnstyl serve --port 8787 --db <path>
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import typer
from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from . import jobtypes
from . import schema as S
from .engine import Engine, Outcome
from .memory import DB_PATH_ENV_VAR as DB_PATH_ENV_VAR_MEMORY
from .memory import PROJECT_ROOT
from .payments import explorer_address, explorer_tx

load_dotenv()

# Camera-friendly width. Rich otherwise fills the terminal, which makes panels
# too wide to read on a recording. TURNSTYL_WIDTH (or --narrow) caps it.
CAMERA_WIDTH = 100
WIDTH_ENV_VAR = "TURNSTYL_WIDTH"


def _configured_width() -> int | None:
    raw = os.environ.get(WIDTH_ENV_VAR)
    if not raw or not raw.strip():
        return None
    try:
        value = int(raw.strip())
    except ValueError:
        raise RuntimeError(
            f"turnstyl: {WIDTH_ENV_VAR} must be a whole number of columns, got "
            f"{raw!r}. Unset it or set something like {WIDTH_ENV_VAR}={CAMERA_WIDTH}."
        ) from None
    if value < 40:
        raise RuntimeError(
            f"turnstyl: {WIDTH_ENV_VAR}={value} is too narrow to render a panel; "
            f"use 40 or more."
        )
    return value


console = Console(width=_configured_width())
err_console = Console(stderr=True)


def panel_width() -> int:
    """Never wider than a recording can show, whatever the terminal is."""
    return min(console.width, CAMERA_WIDTH)

app = typer.Typer(
    add_completion=False,
    no_args_is_help=True,
    help="turnstyl - a metered audit agent that gets paid per step.",
)
job_app = typer.Typer(add_completion=False, no_args_is_help=True, help="Job commands.")
app.add_typer(job_app, name="job")


@app.callback()
def main_options(
    narrow: bool = typer.Option(
        False,
        "--narrow",
        help=f"Cap output at {CAMERA_WIDTH} columns for recording.",
    ),
) -> None:
    """turnstyl - a metered audit agent that gets paid per step."""
    if narrow:
        console.width = CAMERA_WIDTH

DECISION_STYLE = {
    S.RUN_FREE: "cyan",
    S.RUN_PAID: "green",
    S.RUN_ON_CREDIT: "yellow",
    S.WAIT_FOR_PAYMENT: "magenta",
    S.REFUSE: "red",
    "RESUME_EXISTING": "cyan",
    "SKIP_ALREADY_DONE": "cyan",
    "ALREADY_COMPLETE": "cyan",
}


def agent_address() -> str:
    """The address a buyer pays. Public by definition; no secret is ever read."""
    return os.environ.get("AGENT_ADDRESS") or "(AGENT_ADDRESS not set in .env)"


def render_memory_read(outcome: Outcome) -> None:
    if outcome.memory_read:
        console.print(
            Text(f"memory read: {', '.join(outcome.memory_read)}", style="dim")
        )


def render_decision(outcome: Outcome) -> None:
    """The verdict: one plain sentence, the DECISION line for the camera, then
    the full reason in dim text below it."""
    if not outcome.decision:
        return
    if outcome.summary:
        console.print(Text(outcome.summary))
    style = DECISION_STYLE.get(outcome.decision, "white")
    line = Text("DECISION: ", style="bold")
    line.append(outcome.decision, style=f"bold {style}")
    console.print(line)
    if outcome.reason:
        console.print(Text(f"because {outcome.reason}", style="dim"))


def render_step(outcome: Outcome) -> None:
    if outcome.output is None or outcome.step is None:
        return
    served = "from memory (cached)" if outcome.cached else "from the model"
    subtitle = (
        f"{served} | {outcome.tokens} tokens | {outcome.seconds:.2f}s | "
        f"{outcome.price_usdc:.2f} USDC | sha256 {S.sha256_text(outcome.output)[:12]}"
    )
    if outcome.tests_total is not None:
        # A suite that runs is the gate; failing tests may be documenting real
        # defects, so the counts go in the panel rather than a pass/fail verdict.
        subtitle += (
            f" | TESTS: {outcome.tests_passed} passed, {outcome.tests_failed} failed"
        )
    elif outcome.compiles is not None:
        # The gated step's mechanical verdict belongs with the step's other facts,
        # inside the panel it describes. The diff is generated by turnstyl so it
        # always applies; whether it compiles is the real question.
        label = "TESTS COMPILE" if outcome.step_name == "tests" else "PATCH COMPILES"
        subtitle += f" | {label}: {'yes' if outcome.compiles else 'no'}"
    console.print(
        Panel(
            # Text(), not a bare str: step output is Solidity, and rich would
            # read `balances[msg.sender]` as console markup and eat the index.
            Text(outcome.output),
            title=f"STEP {outcome.step}: {outcome.step_name or outcome.step}",
            subtitle=subtitle,
            border_style="cyan",
            padding=(1, 2),
            width=panel_width(),
        )
    )


def render_invoice(
    invoice: S.OpenInvoice | None,
    price_reason: str = "",
    engine: Engine | None = None,
    job_id: str | None = None,
    job_type: str | None = None,
) -> None:
    if invoice is None:
        return
    spec = jobtypes.get(job_type)
    backend = engine.payments if engine is not None else None
    payee = backend.payee_address() if backend else agent_address()
    reason = price_reason or invoice.price_reason
    body = Table.grid(padding=(0, 2))
    body.add_column(style="dim", justify="right")
    body.add_column()
    body.add_row("step", f"{invoice.step} ({spec.step_name(invoice.step)})")
    body.add_row("amount", f"{invoice.amount_usdc:.2f} USDC")
    body.add_row("pay to", payee)
    body.add_row("memo", invoice.memo)
    body.add_row("status", "settled" if invoice.paid else "unpaid")
    if reason:
        body.add_row("priced", Text(reason))
    if backend is not None and job_id:
        body.add_row("buyer runs", backend.buyer_command(job_id, invoice.step))
    console.print(
        Panel(
            body,
            title="INVOICE",
            border_style="yellow",
            padding=(1, 2),
            width=panel_width(),
        )
    )


def render_commit(outcome: Outcome) -> None:
    """The receipt for what was just delivered."""
    if outcome.commit_tx and outcome.commit_hash:
        line = Text("COMMITTED ", style="bold green")
        line.append(outcome.commit_hash[:10])
        line.append(" tx ")
        line.append(outcome.commit_tx)
        console.print(line)
        console.print(Text(explorer_tx(outcome.commit_tx), style="dim"))
    elif outcome.commit_error:
        console.print(
            Text(
                f"WARNING: on-chain commit failed and was skipped: "
                f"{outcome.commit_error}",
                style="bold yellow",
            )
        )
        console.print(
            Text(
                "The step output is recorded in memory; only its on-chain receipt "
                "is missing.",
                style="dim",
            )
        )


def render_reconciled(outcome_or_list) -> None:
    items = (
        outcome_or_list
        if isinstance(outcome_or_list, list)
        else outcome_or_list.reconciled
    )
    for item in items:
        line = Text("RECONCILED ", style="bold green")
        line.append(
            f"step {item['step']} of job {item['job_id']} "
            f"({item['amount_usdc']:.2f} USDC) settled on chain"
        )
        console.print(line)
        console.print(Text(explorer_tx(item["tx_hash"]), style="dim"))


def render_injection(outcome: Outcome, engine: Engine | None = None) -> None:
    """Say it before anything else if the source tried to instruct the auditor."""
    if engine is None or not outcome.job_id:
        return
    state = engine.store.get_job_state(outcome.job_id)
    flags = list(state.injection_flags) if state else []
    if not flags:
        return
    lines = [
        "This contract contains text that tries to instruct the auditor. Found "
        "by a mechanical scan of its comments and strings before any model saw "
        "it, recorded on the job, and handed to the audit as evidence.",
        "",
    ]
    for flag in flags[:8]:
        lines.append(f"line {flag.line:>4}  {flag.rule:<20} {flag.matched or flag.text[:70]}")
    if len(flags) > 8:
        lines.append(f"... and {len(flags) - 8} more")
    console.print(
        Panel(
            "\n".join(lines),
            title=f"UNTRUSTED SOURCE: {len(flags)} flagged passage(s)",
            border_style="red",
            padding=(1, 2),
            width=panel_width(),
        )
    )


def render_outcome(outcome: Outcome, engine: Engine | None = None) -> None:
    render_reconciled(outcome)
    render_injection(outcome, engine)
    for hint in outcome.memory_hints:
        console.print(Text(f"memory hint: {hint}", style="dim"))
    render_step(outcome)
    render_commit(outcome)
    render_invoice(
        outcome.invoice, outcome.price_reason, engine, outcome.job_id, outcome.job_type
    )
    if outcome.complete:
        console.print(
            Panel(
                f"Job {outcome.job_id} is complete. All "
                f"{jobtypes.get(outcome.job_type).last_step} outputs are cached in "
                f"memory under {outcome.job_type} for this contract hash; a repeat "
                f"{outcome.job_type} job on the same contract is served from memory "
                f"at half price.",
                title="COMPLETE",
                border_style="green",
                padding=(1, 2),
            )
        )
    elif outcome.note:
        console.print(Text(outcome.note, style="dim"))
    # Last two lines on screen: what memory said, then the verdict it produced.
    render_memory_read(outcome)
    render_decision(outcome)


def fail(message: str) -> None:
    err_console.print(Text(message, style="bold red"))
    raise typer.Exit(code=1)


def build_engine() -> Engine:
    try:
        return Engine()
    except Exception as e:  # surfaced with the path so an operator can act
        fail(f"turnstyl: could not start the engine: {type(e).__name__}: {e}")
        raise


@app.command("types")
def types() -> None:
    """List the services on offer, with their steps and prices."""
    for spec in jobtypes.all_types():
        grid = Table.grid(padding=(0, 2))
        grid.add_column(style="dim", justify="right")
        grid.add_column()
        for step in spec.steps:
            gate = "" if step.gate == "none" else f"  [{step.gate} gate]"
            grid.add_row(
                f"step {step.n}",
                f"{step.name:<10} {step.base_price_usdc:.2f} USDC{gate}",
            )
        grid.add_row("total", f"{sum(s.base_price_usdc for s in spec.steps):.2f} USDC")
        grid.add_row("run", f"turnstyl job new <file> --buyer <addr> --type {spec.id}")
        console.print(
            Panel(
                grid,
                title=f"{spec.id}  ({spec.name})",
                subtitle=spec.description,
                border_style="cyan",
                padding=(1, 2),
                width=panel_width(),
            )
        )


@job_app.command("new")
def job_new(
    contract: str = typer.Argument(..., help="Path to the Solidity contract."),
    buyer: str = typer.Option(..., "--buyer", help="Buyer wallet address."),
    job_type: str = typer.Option(
        jobtypes.DEFAULT_TYPE_ID, "--type", help="Service id; see 'turnstyl types'."
    ),
) -> None:
    """Start a job, or resume the open one for this contract and service."""
    engine = build_engine()
    try:
        outcome = engine.new_job(contract, buyer, job_type)
    except Exception as e:
        fail(f"turnstyl: {e}")
        raise
    console.print(
        Text(
            f"job {outcome.job_id}  type {outcome.job_type}  "
            f"buyer {engine.store.buyer_key(buyer)}",
            style="dim",
        )
    )
    render_outcome(outcome, engine)


@job_app.command("run")
def job_run(job_id: str = typer.Argument(..., help="Job id from 'job new'.")) -> None:
    """Run the current step of a job."""
    engine = build_engine()
    try:
        outcome = engine.run(job_id)
    except Exception as e:
        fail(f"turnstyl: {e}")
        raise
    console.print(
        Text(
            f"job {outcome.job_id}  type {outcome.job_type}  "
            f"status {outcome.status}",
            style="dim",
        )
    )
    render_outcome(outcome, engine)


@app.command("pay")
def pay(
    job_id: str = typer.Argument(..., help="Job id."),
    step: int = typer.Argument(..., help="Step number to settle (2, 3 or 4)."),
    tx: str = typer.Option(None, "--tx", help="Transaction hash to record."),
) -> None:
    """Settle an invoice. Fake payment backend only."""
    engine = build_engine()
    try:
        tx_hash = engine.pay(job_id, step, tx)
    except NotImplementedError as e:
        fail(f"turnstyl: {e}")
        raise
    except Exception as e:
        fail(f"turnstyl: {e}")
        raise
    console.print(
        Panel(
            f"step {step} of job {job_id} marked paid\ntx {tx_hash}",
            title="PAYMENT RECORDED",
            border_style="green",
            padding=(1, 2),
        )
    )


@app.command("ledger")
def ledger(buyer: str = typer.Argument(..., help="Buyer wallet address.")) -> None:
    """Print what memory knows about one buyer."""
    engine = build_engine()
    data = engine.ledger(buyer)
    render_reconciled(data.get("reconciled", []))
    book = data["ledger"]
    if not data["known"]:
        console.print(
            Text(
                f"No ledger for {data['buyer']} in {engine.store.db_path}. "
                f"This buyer is unknown to memory.",
                style="yellow",
            )
        )
        return

    grid = Table.grid(padding=(0, 2))
    grid.add_column(style="dim", justify="right")
    grid.add_column()
    grid.add_row("buyer", data["buyer"])
    grid.add_row("paid steps", str(book.paid_steps))
    grid.add_row("paid", f"{book.paid_usdc:.2f} USDC")
    grid.add_row("open invoices", str(book.open_invoices))
    grid.add_row("unpaid from prior jobs", str(book.unpaid_from_prior_jobs))
    grid.add_row("defaults on record", str(book.defaults))
    grid.add_row("completed paid jobs", str(book.completed_paid_jobs))
    if book.defaults:
        grid.add_row(
            "clean paid steps since",
            f"{book.consecutive_paid_since_default} "
            f"(credit returns at {S.EARN_BACK_PAID_STEPS})",
        )
    grid.add_row("trust tier", book.trust_tier)
    grid.add_row("jobs", str(len(book.jobs)))
    console.print(Panel(grid, title="LEDGER", border_style="cyan", padding=(1, 2)))

    job_types = {j["job_id"]: j.get("job_type") for j in data["jobs"]}
    if book.outstanding:
        table = Table(title="OUTSTANDING", border_style="yellow")
        table.add_column("job")
        table.add_column("step")
        table.add_column("amount USDC", justify="right")
        for item in book.outstanding:
            table.add_row(
                item.job_id,
                f"{item.step} ({jobtypes.get(job_types.get(item.job_id)).step_name(item.step)})",
                f"{item.amount_usdc:.2f}",
            )
        console.print(table)

    if data["jobs"]:
        table = Table(title="JOBS", border_style="cyan")
        table.add_column("job")
        table.add_column("status")
        table.add_column("step", justify="right")
        table.add_column("steps recorded")
        table.add_column("contract")
        for job in data["jobs"]:
            table.add_row(
                job["job_id"],
                job["status"],
                str(job["current_step"]),
                ",".join(job["steps_recorded"]) or ("archived" if job["archived"] else "-"),
                job["contract_hash"][:12],
            )
        console.print(table)
    console.print(Text(f"memory read: {', '.join(data['memory_read'])}", style="dim"))


@app.command("worker")
def worker(
    db: str = typer.Option(
        None, "--db", help="Database to watch. Defaults to $TURNSTYL_DB."
    ),
    interval: float = typer.Option(3.0, "--interval", help="Seconds between passes."),
    once: bool = typer.Option(False, "--once", help="One pass, then exit."),
) -> None:
    """Run active jobs automatically as their invoices are settled.

    Every pass reconciles each buyer and runs the current step of any job the
    policy would run, through the same engine as `job run`. Waiting jobs are
    looked at but not written about. Ctrl-C stops it cleanly.
    """
    from .worker import main as worker_main

    if db:
        os.environ[DB_PATH_ENV_VAR_MEMORY] = db
    announce_memory()
    raise typer.Exit(code=worker_main(None, interval, once))


def announce_memory() -> None:
    """Create the store if it is absent and say which one is in use.

    Startup is the only moment turnstyl creates a database on purpose. The
    API and the worker loop refuse to recreate one that disappears while they
    run, so the delete beat stays a real loss.
    """
    from .memory import bootstrap_memory

    try:
        path, created, records = bootstrap_memory()
    except Exception as e:  # surfaced with the path so an operator can act
        fail(f"turnstyl: could not open or create the memory file: {type(e).__name__}: {e}")
        raise
    # soft_wrap: these lines are grepped from logs, and Rich would otherwise
    # fold a long path onto a second line when stdout is not a terminal.
    if created:
        console.print(Text(f"memory: created {path}", style="dim"), soft_wrap=True)
    else:
        console.print(Text(f"memory: using {path} ({records} records)", style="dim"), soft_wrap=True)


@app.command("serve")
def serve(
    host: str = typer.Option("127.0.0.1", "--host", help="Interface to bind."),
    port: int = typer.Option(8787, "--port", help="Port to listen on."),
    db: str = typer.Option(
        None, "--db", help="Database to read. Defaults to $TURNSTYL_DB."
    ),
    with_worker: bool = typer.Option(
        False, "--with-worker", help="Also run the worker loop in this process."
    ),
    interval: float = typer.Option(
        3.0, "--interval", help="Worker pass interval in seconds (with --with-worker)."
    ),
) -> None:
    """Serve the web view of this agent's memory.

    Binds 127.0.0.1 unless --host says otherwise. GET endpoints never write; POST /api/jobs hands a
    contract to the engine exactly as `job new` does. With --with-worker the
    worker loop runs in a background thread of the same process, so the demo
    is one command.
    """
    import uvicorn

    if db:
        # api.py resolves the path per request, so setting it here is enough.
        os.environ[DB_PATH_ENV_VAR_MEMORY] = db

    # Bind-check first: uvicorn reports "address already in use" only after we
    # would have printed a URL that serves someone else's process.
    import socket

    probe = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    probe.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        probe.bind((host, port))
    except OSError as e:
        probe.close()
        fail(
            f"turnstyl: cannot serve on {host}:{port}: {e}.\n"
            f"  Something is already listening there. Find it with "
            f"'lsof -nP -iTCP:{port} -sTCP:LISTEN', or pass a different --port."
        )
        raise
    probe.close()

    console.print(
        Text(f"turnstyl serving http://{host}:{port}", style="bold"), soft_wrap=True
    )
    announce_memory()
    if with_worker:
        from .worker import start_in_thread

        start_in_thread(None, interval)
    uvicorn.run("turnstyl.api:app", host=host, port=port, log_level="warning")


@app.command("reset")
def reset(
    db: str = typer.Option(..., "--db", help="Path to the turnstyl database to delete."),
) -> None:
    """Delete a turnstyl memory store. This is the delete test.

    Reports what the store held before removing it, so what is being destroyed
    is on the record. Refuses any path outside ./data/.
    """
    import sqlite3

    target = Path(db).expanduser()
    data_dir = (PROJECT_ROOT / "data").resolve()
    try:
        resolved = target.resolve()
    except OSError as e:
        fail(f"turnstyl: cannot resolve {target}: {e}")
        raise
    if resolved.parent != data_dir:
        fail(
            f"turnstyl: refusing to delete {resolved}.\n"
            f"  reset only removes databases directly inside {data_dir}."
        )
    if not resolved.is_file():
        fail(
            f"turnstyl: no database at {resolved}. Nothing to delete.\n"
            f"  Run '.venv/bin/turnstyl status' to see which store is in use."
        )

    size = resolved.stat().st_size
    # Counted with sqlite3 rather than the SDK: there is no public API that
    # lists state keys, and this has to read all three tables before the file
    # stops existing.
    try:
        conn = sqlite3.connect(f"file:{resolved}?mode=ro", uri=True)
        count = lambda sql: conn.execute(sql).fetchone()[0]  # noqa: E731
        states = count("SELECT count(*) FROM state_documents")
        entities = count("SELECT count(*) FROM entities")
        archived = count("SELECT count(*) FROM archived_entities")
        events = count("SELECT count(*) FROM journal_events")
        conn.close()
    except sqlite3.Error as e:
        fail(
            f"turnstyl: {resolved} is not a readable turnstyl database ({e}).\n"
            f"  Refusing to delete a file this command cannot account for."
        )
        raise

    grid = Table.grid(padding=(0, 2))
    grid.add_column(style="dim", justify="right")
    grid.add_column()
    grid.add_row("database", str(resolved))
    grid.add_row("size", f"{size:,} bytes")
    grid.add_row("state keys", str(states))
    grid.add_row("entities", f"{entities} live, {archived} archived")
    grid.add_row("journal events", str(events))
    console.print(
        Panel(
            grid,
            title="ABOUT TO DELETE",
            border_style="red",
            padding=(1, 2),
            width=panel_width(),
        )
    )

    removed = []
    for suffix in ("", "-wal", "-shm"):
        sidecar = Path(str(resolved) + suffix)
        if sidecar.exists():
            sidecar.unlink()
            removed.append(sidecar.name)
    if resolved.exists():
        fail(f"turnstyl: failed to delete {resolved}; it is still on disk.")

    console.print(
        Text(
            f"memory deleted: {resolved} ({entities} entities, {events} "
            f"journal events gone)",
            style="bold red",
        )
    )


@app.command("status")
def status() -> None:
    """List the active jobs held in memory."""
    engine = build_engine()
    data = engine.status()
    if not data["active_jobs"]:
        console.print(
            Text(f"No active jobs in {data['db_path']}.", style="yellow")
        )
        return
    table = Table(title="ACTIVE JOBS", border_style="cyan")
    table.add_column("job")
    table.add_column("buyer")
    table.add_column("status")
    table.add_column("step", justify="right")
    table.add_column("open invoice")
    table.add_column("contract")
    for state in data["active_jobs"]:
        invoice = state.open_invoice
        table.add_row(
            state.job_id,
            state.buyer,
            state.status,
            f"{state.current_step}/{jobtypes.get(state.job_type).last_step}",
            f"{invoice.amount_usdc:.2f} USDC step {invoice.step}" if invoice else "-",
            state.contract_hash[:12],
        )
    console.print(table)
    if data["orphans"]:
        console.print(
            Text(
                f"warning: {len(data['orphans'])} active job id(s) have no state "
                f"document: {', '.join(data['orphans'])}",
                style="red",
            )
        )
    console.print(Text(f"memory read: {', '.join(data['memory_read'])}", style="dim"))


def main() -> None:
    app()


if __name__ == "__main__":
    main()
